version: "3"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        npm install && jupyter lab \
        --port=8888 \
        --ip=* \
        --no-browser \
        --NotebookApp.token='' \
        --allow-root \
        --notebook-dir=/workspace
      "
    ports:
      - "8888:8888"
      - "8880:8880"
    volumes:
      - ./workspace:/workspace
    working_dir: "/workspace"
  mcserver:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      DIFFICULTY: "peaceful"
      OPS: "shino_hinaduki,stackstuck"
    ports:
      - "25565:25565"
    volumes:
      - ./mcserver-data:/data
