version: "3"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter lab
      --port=8888
      --ip=*
      --no-browser
      --NotebookApp.token=''
      --allow-root
      --notebook-dir=/workspace
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace
  mcserver:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "TRUE"
      DIFFICULTY: "peaceful"
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./mcserver-data:/data
